
 spring:

   application:

     name: latte

   datasource:
     
     url: "${SPRING_DATASOURCE_URL}"
     username: "${SPRING_DATASOURCE_USERNAME}"
     password: "${SPRING_DATASOURCE_PASSWORD}"

   jpa:

     database-platform: org.hibernate.dialect.MariaDBDialect

     hibernate:

       ddl-auto: update

     show-sql: true

 server:

   servlet:

     context-path: /latte/api/v1
