
 spring:

   datasource:

     url: jdbc:mariadb://localhost:3306/LatteIceCream
     username: "admin"
     password: "+V$u].M¿r=" 
     # password: "${DB_PASSWORD}"

   jpa:

     database-platform: org.hibernate.dialect.MariaDBDialect

     hibernate:

       ddl-auto: update

     show-sql: true
