
 spring:

   datasource:

     url: jdbc:mariadb://localhost:3306/LatteIceCream
     username: ""
     password: "${DB_PASSWORD}"

   jpa:

     database-platform: org.hibernate.dialect.MariaDBDialect

     hibernate:

       ddl-auto: update

     show-sql: true
